### ISSUE TITLE
Local Skynet Portal

### ISSUE THREAD

**Issue by ihmc3jn09hk** [SkynetLabs/skynet-js#348]
Hello, I am trying to have some more experience with Skynet. I read the [guides](https://siasky.net/docs/?javascript--browser#using-the-skynet-client) but still no description on setting up local skynet portal/node. It is not described in the [demo example](https://blog.sia.tech/creating-your-first-web-app-on-skynet-ec6f4fff405f) too. Am I missing something ?

Could you please share the guide on creating local nodes/portals other than `https://siasky.net`?

**Comment by m-cat** [comment]
@ihmc3jn09hk The guides you linked to are for interacting with the official Skynet portal `siasky.net`. In order to run a local portal, please refer to [this documentation](https://docs.siasky.net/developer-guides/operating-a-skynet-webportal).

Closing as this is the repo for the SDK and not the portal. If you run into any issues or have any further questions, please go to the [portal repo](https://github.com/SkynetLabs/skynet-webportal).
