### ISSUE TITLE
Refused to set unsafe header 'Cookie'

### ISSUE THREAD

**Issue by mahesh8488** [SkynetLabs/skynet-js#376]
When pinning the skynet link after uploading, I get the error

Refused to set unsafe header 'Cookie'

Documentation:
https://docs.siasky.net/developer-guides/server-hosted-skynet-usage#re-pining-a-skylink-using-your-account-with-skynet-js

**Comment by mahesh8488** [comment]
Instead of using pinSkylink, I tried using the fetch API. I am seeing a 204, but cant see the file in my portal account. Am I missing anything here ?

await fetch("https://siasky.net/skynet/pin/XYZ" , {
          method: "POST",
          headers: {
            'Content-Type': 'application/json',
            'Cookie': "skynet-jwt=<MyCookieFromSkynetAccount>"
          },
        });

**Comment by m-cat** [comment]
For your second problem, you have to follow the documentation and obtain the full JWT. `skynet-jwt=` is not a complete JWT.

**Comment by mahesh8488** [comment]
I have fetched and passed the jwt token correctly, just didn’t add it in example above. Btw I do get the call working but with a 204 response code. I did some more digging and found that the cookie is dropped before making the call. Not sure why ! I have tried options like setting the cookie and passing credential:include while making call

**Comment by m-cat** [comment]
Before I investigate further can you please let me know what version of `skynet-js` you are using, along with your browser?

**Comment by mahesh8488** [comment]
"skynet-js": "^4.0.22-beta",

**Comment by mahesh8488** [comment]
> Before I investigate further can you please let me know what version of `skynet-js` you are using, along with your browser?

Nvm regarding the second issue: I was able to workaround the problem. The issue is browser will not send cookies for cross site. I made an API call where I handled pinning.

**Comment by m-cat** [comment]
Hey, sorry for the delay. The issue is that `Cookie` is a forbidden header name and setting it directly doesn't work in browsers. https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name The `customCookie` option is a bit old and was meant for server-side use. The docs are also a bit misleading by mentioning `skynet-js` and I've brought that up with the author.

Please sign in to an account at `account.siasky.net`, then the cookie will be set automatically with all requests and you'll see uploads show up in your account. The only caveat is that your skapp needs to run from the same domain. 

Hope that helps -- let me know if you still have any concerns.

**Comment by mahesh8488** [comment]
Yep the documentation was misleading. I used a workaround of calling a web service i own, which in turn makes a webrequest to call the /skynet/pin API. Used the cookie there!
